import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import AuthContextProvider from "@/components/auth-provider";
import Header from "./(root)/_components/header";
import { Toaster } from "react-hot-toast";
import EventContextProvider from "@/components/event-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "EVENTS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
      <EventContextProvider>
        <AuthContextProvider>
              <ThemeProvider       
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
              >
                <main>
                  <Header/>
                  <Toaster />
                  {children}
                </main>
              </ThemeProvider>
        </AuthContextProvider>
      </EventContextProvider>
      </body>
    </html>
  );
}
